### ISSUE TITLE
[Spree 2.1] EnterprisesController missing routes

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/ofn-install#630]
Errors:

```
  1) EnterprisesController as an enterprise owner creating an enterprise creates as sells=any when it is not a producer
     Failure/Error: spree_post :create, { enterprise: new_enterprise_params }
     
     AbstractController::ActionNotFound:
       The action 'create' could not be found for EnterprisesController
     # ./spec/controllers/api/enterprises_controller_spec.rb:33:in `block (4 levels) in <module:Api>'

  2) EnterprisesController as an enterprise owner creating an enterprise saves all user ids submitted
     Failure/Error:
       spree_post :create, {
         enterprise: new_enterprise_params.
           merge({ user_ids: [enterprise_owner.id, manager1.id, manager2.id] })
       }
     
     AbstractController::ActionNotFound:
       The action 'create' could not be found for EnterprisesController
     # ./spec/controllers/api/enterprises_controller_spec.rb:43:in `block (4 levels) in <module:Api>'

  3) EnterprisesController as an enterprise manager submitting a valid image I can update enterprise image
     Failure/Error: spree_post :update_image, logo: 'a logo', id: enterprise.id
     
     AbstractController::ActionNotFound:
       The action 'update_image' could not be found for EnterprisesController
     # ./spec/controllers/api/enterprises_controller_spec.rb:71:in `block (4 levels) in <module:Api>'

  4) EnterprisesController as an non-managing user submitting a valid image I can't update enterprise image
     Failure/Error: spree_post :update_image, logo: 'a logo', id: enterprise.id
     
     AbstractController::ActionNotFound:
       The action 'update_image' could not be found for EnterprisesController
     # ./spec/controllers/api/enterprises_controller_spec.rb:90:in `block (4 levels) in <module:Api>'
```

**Comment by Matt-Yorkley** [comment]
These all pass locally as well. This is looking very similar to: https://github.com/openfoodfoundation/openfoodnetwork/issues/5504

I have no idea how the routes for random controllers could occasionally fail to be found and sometimes not...?
