### ISSUE TITLE
OFN 4.1.14 to 4.1.15 fails update "Could not find mini_portile2-2.7.1"

### ISSUE THREAD

**Issue by romale** [openfoodfoundation/ofn-install#847]
## Description

Hi.
I try to update OFN from 4.1.14 to 4.1.15, but it fail
In release note i see "If you're running an instance that's not managed by the core team, you'll need to provision with the latest ofn-install before deploying" and i did provision.
But when i run ansible-playbook playbooks/deploy.yml --limit ru-staging -e "git_version=v4.1.15" , i gget this error:

```
TASK [deploy : clear transient data] ******************************************************************************************************************************************************************************
fatal: [dev.openfoodnetwork.ru]: FAILED! => {"changed": true, "cmd": ["bash", "-lc", "bundle exec rake ofn:data:remove_transient_data RAILS_ENV=production"], "delta": "0:00:00.942426", "end": "2022-12-04 18:29:48.857316", "msg": "non-zero return code", "rc": 1, "start": "2022-12-04 18:29:47.914890", "stderr": "bundler: failed to load command: rake (/home/openfoodnetwork/.gem/ruby/3.0.0/bin/rake)\nBundler::GemNotFound: Could not find mini_portile2-2.7.1 in any of the sources\n  /home/openfoodnetwork/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:86:in `block in materialize'\n  /home/openfoodnetwork/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `map!'\n  /home/openfoodnetwork/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `materialize'\n  /home/openfoodnetwork/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/definition.rb:170:in `specs'\n  /home/openfoodnetwork/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/definition.rb:237:in `specs_for'\n  /home/openfoodnetwork/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/definition.rb:226:in `requested_specs'\n  /home/openfoodnetwork/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:101:in `block in definition_method'\n  /home/openfoodnetwork/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:20:in `setup'\n  /home/openfoodnetwork/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler.rb:149:in `setup'\n  /home/openfoodnetwork/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `block in <top (required)>'\n  /home/openfoodnetwork/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136:in `with_level'\n  /home/openfoodnetwork/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88:in `silence'\n  /home/openfoodnetwork/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `<top (required)>'", "stderr_lines": ["bundler: failed to load command: rake (/home/openfoodnetwork/.gem/ruby/3.0.0/bin/rake)", "Bundler::GemNotFound: Could not find mini_portile2-2.7.1 in any of the sources", "  /home/openfoodnetwork/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:86:in `block in materialize'", "  /home/openfoodnetwork/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `map!'", "  /home/openfoodnetwork/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `materialize'", "  /home/openfoodnetwork/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/definition.rb:170:in `specs'", "  /home/openfoodnetwork/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/definition.rb:237:in `specs_for'", "  /home/openfoodnetwork/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/definition.rb:226:in `requested_specs'", "  /home/openfoodnetwork/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:101:in `block in definition_method'", "  /home/openfoodnetwork/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:20:in `setup'", "  /home/openfoodnetwork/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler.rb:149:in `setup'", "  /home/openfoodnetwork/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `block in <top (required)>'", "  /home/openfoodnetwork/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136:in `with_level'", "  /home/openfoodnetwork/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88:in `silence'", "  /home/openfoodnetwork/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `<top (required)>'"], "stdout": "", "stdout_lines": []}
Sunday 04 December 2022  18:29:47 +0300 (0:00:01.243)       0:02:09.088 *******
```

In slack i wrote that update from 4.1.8 to 4.2.23 is success, but later checks show me that i can't change item images, because of 500 error. So, i start update OFN step by step from 4.1.8 to major versions.

## Expected Behavior

Success update to 4.1.15

## Actual Behaviour

Update fails

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

Ubuntu 16
OFN 4.1.14

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by mkllnk** [comment]
Closing due to inactivity.
